/**
 * Sample bank-supplied documents, shared by the reader tests and the
 * end-to-end parse test so the two cannot drift apart.
 *
 * The OFX fixtures are 1.x SGML on purpose: that is the flavour banks actually
 * ship (unclosed leaf tags, a plain-text header block), and it is the one that
 * a naive XML parser cannot read. The camt fixtures are well-formed XML with a
 * namespace, which is the other real shape.
 */

// A bank current-account statement: two accounts and two periods in one file,
// which is exactly what a bank produces when it appends every page to a single
// download. Leaf tags are unclosed, as SGML requires.
export const OFX_TWO_ACCOUNTS = `OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
<SIGNONMSGSRSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO</STATUS>
<DTSSERVER>20260531120000<LANGUAGE>ENG</SONRS></SIGNONMSGSRSV1>
<BANKMSGSRSV1>
<STMTTRNRS>
<TRNUID>1001<STATUS><CODE>0<SEVERITY>INFO</STATUS>
<STMTRS>
<CURDEF>INR
<BANKACCTFROM><BANKID>HDFC0001<ACCTID>50100234567890<ACCTTYPE>SAVINGS</BANKACCTFROM>
<BANKTRANLIST>
<DTSTART>20260501<DTEND>20260531
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260518
<TRNAMT>-1250.50
<FITID>HDFC20260518001
<NAME>SWIGGY ORDER
<MEMO>Order 4471
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260520
<TRNAMT>75000.00
<FITID>HDFC20260520002
<NAME>SALARY
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260522
<TRNAMT>-99.99
<FITID>HDFC20260522003
<NAME>CHARGES
</STMTTRN>
</BANKTRANLIST>
<LEDGERBAL><BALAMT>73749.51<DTASOF>20260531</LEDGERBAL>
<AVAILBAL><BALAMT>72749.51<DTASOF>20260531</AVAILBAL>
</STMTRS>
</STMTTRNRS>
<STMTTRNRS>
<TRNUID>1002<STATUS><CODE>0<SEVERITY>INFO</STATUS>
<STMTRS>
<CURDEF>INR
<BANKACCTFROM><BANKID>HDFC0001<ACCTID>50100999888777<ACCTTYPE>SAVINGS</BANKACCTFROM>
<BANKTRANLIST>
<DTSTART>20260401<DTEND>20260430
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260414
<TRNAMT>-200.00
<FITID>HDFC20260414001
<NAME>RENT
</STMTTRN>
</BANKTRANLIST>
<LEDGERBAL><BALAMT>1200.00<DTASOF>20260430</LEDGERBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
`;

// A credit-card statement: the CC flavour carries no BANKACCTFROM, and its
// TRNAMT signs are the other way round from a bank current account.
export const OFX_CREDIT_CARD = `OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
<CCMSGSRSV1><CCSTMTRS>
<CURDEF>INR
<CCACCTFROM><ACCTID>XXXX5678</CCACCTFROM>
<BANKTRANLIST>
<DTSTART>20260501<DTEND>20260531
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260503
<TRNAMT>-2499.00
<FITID>CC20260503001
<NAME>AMAZON
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260509
<TRNAMT>150.00
<FITID>CC20260509002
<NAME>REFUND AMAZON
</STMTTRN>
</BANKTRANLIST>
<LEDGERBAL><BALAMT>38150.25<DTASOF>20260531</LEDGERBAL>
</CCSTMTRS></CCMSGSRSV1>
</OFX>
`;

// A bank that reports an explicit DEBIT with a positive amount. The sign and
// the type disagree, and the type is the more explicit statement.
export const OFX_SIGN_DISAGREES = `OFXHEADER:100
DATA:OFXSGML
CHARSET:1252

<OFX>
<BANKMSGSRSV1>
<STMTTRNRS>
<STMTRS>
<CURDEF>INR
<BANKACCTFROM><ACCTID>1111222233334444<ACCTTYPE>SAVINGS</BANKACCTFROM>
<BANKTRANLIST>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260518<TRNAMT>500.00<FITID>A1<NAME>POSITIVE DEBIT</STMTTRN>
<STMTTRN><TRNTYPE>XFER<DTPOSTED>20260519<TRNAMT>-300.00<FITID>A2<NAME>SALARY CREDIT</STMTTRN>
</BANKTRANLIST>
<LEDGERBAL><BALAMT>200.00</LEDGERBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
`;

// Rows the reader must refuse rather than invent: no amount, an amount with
// three decimals, no date, an entry with nothing identifying on it at all, and
// one whose only identifier is the bank's own reference (which is enough to
// import, so it is NOT dropped).
export const OFX_MALFORMED_ROWS = `OFXHEADER:100
DATA:OFXSGML
CHARSET:1252

<OFX>
<BANKMSGSRSV1>
<STMTTRNRS>
<STMTRS>
<CURDEF>INR
<BANKACCTFROM><ACCTID>9999<ACCTTYPE>SAVINGS</BANKACCTFROM>
<BANKTRANLIST>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260518<FITID>M1<NAME>NO AMOUNT</STMTTRN>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260518<TRNAMT>10.005<FITID>M2<NAME>THREE DECIMALS</STMTTRN>
<STMTTRN><TRNTYPE>DEBIT<TRNAMT>-10.00<FITID>M3<NAME>NO DATE</STMTTRN>
<STMTTRN><TRNTYPE>DEBIT<FITID>M4</STMTTRN>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260230<TRNAMT>-7.00<NAME>IMPOSSIBLE DATE</STMTTRN>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260518<TRNAMT>-8.00</STMTTRN>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260518<TRNAMT>-9.00<FITID>M7</STMTTRN>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260518<TRNAMT>-42.00<FITID>M5<NAME>GOOD ROW</STMTTRN>
</BANKTRANLIST>
<LEDGERBAL><BALAMT>-42.00</LEDGERBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
`;

// Pending movements a bank lists alongside the booked ones. The ledger has no
// pending state, so these must be reported rather than imported.
export const OFX_WITH_PENDING = `OFXHEADER:100
DATA:OFXSGML
CHARSET:1252

<OFX>
<BANKMSGSRSV1>
<STMTTRNRS>
<STMTRS>
<CURDEF>INR
<BANKACCTFROM><ACCTID>4242<ACCTTYPE>SAVINGS</BANKACCTFROM>
<BANKTRANLIST>
<DTSTART>20260501<DTEND>20260531
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260518<TRNAMT>-25.00<FITID>P1<NAME>BOOKED</STMTTRN>
</BANKTRANLIST>
<INTERIMTRANLIST>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260602<TRNAMT>-99.00<FITID>P2<NAME>PENDING CARD</STMTTRN>
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>20260603<TRNAMT>-12.00<FITID>P3<NAME>PENDING ALSO</STMTTRN>
</INTERIMTRANLIST>
<LEDGERBAL><BALAMT>975.00</LEDGERBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
`;

// Well-formed OFX 2.x, to pin that the same reader handles both flavours.
export const OFX_XML_2 = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?OFX OFXHEADER="200" VERSION="211" SECURITY="NONE" OLDFILEUID="NONE" NEWFILEUID="NONE"?>
<OFX>
  <BANKMSGSRSV1>
    <STMTTRNRS>
      <STMTRS>
        <CURDEF>INR</CURDEF>
        <BANKACCTFROM><BANKID>ICIC0001</BANKID><ACCTID>5555</ACCTID><ACCTTYPE>SAVINGS</ACCTTYPE></BANKACCTFROM>
        <BANKTRANLIST>
          <DTSTART>20260501</DTSTART>
          <DTEND>20260531</DTEND>
          <STMTTRN>
            <TRNTYPE>DEBIT</TRNTYPE>
            <DTPOSTED>20260507</DTPOSTED>
            <TRNAMT>-15.00</TRNAMT>
            <FITID>X1</FITID>
            <NAME>COFFEE</NAME>
          </STMTTRN>
        </BANKTRANLIST>
        <LEDGERBAL><BALAMT>985.00</BALAMT><DTASOF>20260531</DTASOF></LEDGERBAL>
      </STMTRS>
    </STMTTRNRS>
  </BANKMSGSRSV1>
</OFX>
`;

// A statement that parsed cleanly but contains no transactions at all.
export const OFX_NO_TRANSACTIONS = `OFXHEADER:100
DATA:OFXSGML
CHARSET:1252

<OFX>
<BANKMSGSRSV1>
<STMTTRNRS>
<STMTRS>
<CURDEF>INR
<BANKACCTFROM><ACCTID>0000<ACCTTYPE>SAVINGS</BANKACCTFROM>
<BANKTRANLIST>
<DTSTART>20260501<DTEND>20260531
</BANKTRANLIST>
<LEDGERBAL><BALAMT>0.00</LEDGERBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
`;

// A file whose header says it is a different message family entirely.
export const OFX_SERVICES_NOT_STMTRS = `OFXHEADER:100
DATA:OFXSGML
CHARSET:1252

<OFX>
<SERVICEMSGSRSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO</STATUS></SONRS></SERVICEMSGSRSV1>
<BANKMSGSRSV1>
<STMTTRNRS>
<STMTRS>
<CURDEF>INR
<BANKACCTFROM><ACCTID>7777<ACCTTYPE>SAVINGS</BANKACCTFROM>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
`;
